version: '3.8'

services:
  app:
    image: carloser7/assistec-api
    container_name: er7_assistec-api
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - assistec-net
    restart: unless-stopped
  db:
    image: mariadb:10.10
    container_name: er7_assistec-api-db
    restart: always
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: assistenciatec
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3306:3306'
    networks:
      - assistec-net
networks:
  assistec-net:
    driver: bridge