# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: assistenciatec
    ports:
      - 3306:3306
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - dev
      
networks: 
  dev:
    driver: bridge